### ISSUE TITLE
Performance issue in monaco

### ISSUE THREAD

**Issue by alanlichen** [repl-it-discord/repl-it-electron#103]
Usually, when using exports it is supposed to look like this:
![image](https://user-images.githubusercontent.com/40917647/106834650-b1b56400-664a-11eb-8fbd-0e33fd63607e.png)

Occationally, it looks like this: 
![image](https://user-images.githubusercontent.com/40917647/106834618-a2ceb180-664a-11eb-9d3b-2aa7870215ba.png)

I also noticed that other parts were grey, but I did not take screenshots and I forgot where they were

EDIT:
The issue is that
Scrolling is extremely laggy, and when typing text sometimes it takes a few ms to show up. Also, when changing files, it takes around 5 seconds for syntax highlighting to update.

**Comment by spotandjake** [comment]
only occurs on monaco editor also noted that monaco was giving bad performance but ace is fine

**Comment by leon332157** [comment]
It could be something to do with the Theme system, will look into it, thanks.

**Comment by CoolCoderSJ** [comment]
Interesting...also should note that the icon is supposed to be white when viewing the file as this is what I see on the browser version of replit without any external themes
![image](https://user-images.githubusercontent.com/53063247/106835749-e4208a80-6665-11eb-9a73-7e3a2ba80956.png)

**Comment by spotandjake** [comment]
> It could be something to do with the Theme system, will look into it, thanks.

might be how it tokenizes it. I think Monaco uses a background worker thread, to do the tokenization.

**Comment by alanlichen** [comment]
> only occurs on monaco editor also noted that monaco was giving bad performance but ace is fine

Ace highlighting looks different for every export.
![image](https://user-images.githubusercontent.com/40917647/106838498-4622c500-6651-11eb-904e-ea4a61d10de9.png)
![image](https://user-images.githubusercontent.com/40917647/106838509-4b800f80-6651-11eb-8cde-d19403baaa2b.png)

**Comment by spotandjake** [comment]
interesting will look at it can you verify the same thing does not happen on web

**Comment by alanlichen** [comment]
> Also what lang is the exports syntax difference in?

Javascript :)

**Comment by spotandjake** [comment]
> > Also what lang is the exports syntax difference in?
> 
> Javascript :)

interesting will look at it can you verify the same thing does not happen on web

**Comment by spotandjake** [comment]
i will look into this tmr

**Comment by CoolCoderSJ** [comment]
> > Also what lang is the exports syntax difference in?
> 
> Javascript :)

Interesting...the ` exports.run ` is always showing as blue in the monaco editor for me...

**Comment by alanlichen** [comment]
> > > Also what lang is the exports syntax difference in?
> > 
> > 
> > Javascript :)
> 
> Interesting...the `exports.run` is always showing as blue in the monaco editor for me...
> 
> EDIT: Its also showing blue only on the web...

I figured out the issue... I think.
When I add async to the function, it turns blue. When I remove async, it turns green/yellow. This happens on both the web version and editor.

Web version:
with async 
![image](https://user-images.githubusercontent.com/40917647/106839321-d7df0200-6652-11eb-9934-43a43ec0889d.png)
without async
![image](https://user-images.githubusercontent.com/40917647/106839331-dd3c4c80-6652-11eb-94f2-7a04672ba6a2.png)

Electron version:
with async 
![image](https://user-images.githubusercontent.com/40917647/106839351-e75e4b00-6652-11eb-8f34-cf7c8cf5877a.png)
without async 
![image](https://user-images.githubusercontent.com/40917647/106839373-ef1def80-6652-11eb-8cdc-82cb276e9675.png)

**Comment by CoolCoderSJ** [comment]
This seems weird, but if its also happening on the web then its a replit issue and should go [here](https://repl.it/bugs). 

@spotandjake can confirm, but since its also on the web this should probably be closed.

**Comment by spotandjake** [comment]
> This seems weird, but if its also happening on the web then its a replit issue and should go [here](https://repl.it/bugs).
> 
> @spotandjake can confirm, but since its also on the web this should probably be closed.

It agree on the theming but I am gonna leave this open because the performance part is still a thing

**Comment by alanlichen** [comment]
I just don't understand why it's blue on web but grey in the editor

**Comment by alanlichen** [comment]
> > This seems weird, but if its also happening on the web then its a replit issue and should go [here](https://repl.it/bugs).
> > @spotandjake can confirm, but since its also on the web this should probably be closed.
> 
> It agree on the theming but I am gonna leave this open because the performance part is still a thing

I'll just add on to that... Scrolling is extremely laggy, and when typing text sometimes it takes a few ms to show up. Also, when changing files, it takes around 5 seconds for syntax highlighting to update.

**Comment by CoolCoderSJ** [comment]
> 
> 
> > This seems weird, but if its also happening on the web then its a replit issue and should go [here](https://repl.it/bugs).
> > @spotandjake can confirm, but since its also on the web this should probably be closed.
> 
> It agree on the theming but I am gonna leave this open because the performance part is still a thing

ok...does it have to do with your device specs, though, @alanlichen ? Because both editors seem to be working at the same speed for me...are you trying the same repls or different ones? Perhaps the size of one of them is too big?

**Comment by spotandjake** [comment]
They are working fine for me but I still see the performance slow

**Comment by alanlichen** [comment]
> > > This seems weird, but if its also happening on the web then its a replit issue and should go [here](https://repl.it/bugs).
> > > @spotandjake can confirm, but since its also on the web this should probably be closed.
> > 
> > 
> > It agree on the theming but I am gonna leave this open because the performance part is still a thing
> 
> ok...does it have to do with your device specs, though, @alanlichen ? Because both editors seem to be working at the same speed for me...are you trying the same repls or different ones? Perhaps the size of one of them is too big?

Same repl, but ace editor seems to have a massive performance difference.
For now, I guess I will use ace editor :)

**Comment by spotandjake** [comment]
Yah ace editor is way lighter lol but the monaco is better tbh

**Comment by spotandjake** [comment]
Will look into it

**Comment by alanlichen** [comment]
I also want to point out that the colors here are kinda too blue.
![image](https://user-images.githubusercontent.com/40917647/106840175-7750c480-6654-11eb-80fa-ef193ead4e5f.png)

**Comment by alanlichen** [comment]
> Yah ace editor is way lighter lol but the monaco is better tbh

Agree with that 100%, ace runs with extreme lag on my iPad and monaco crashes. Soooo yeah

Also should i rename this to performance issues?

**Comment by spotandjake** [comment]
I hid the color one as that is gonna be a theming thing

**Comment by alanlichen** [comment]
Ok, I should also remove the color one from my issue lol

**Comment by spotandjake** [comment]
> > Yah ace editor is way lighter lol but the monaco is better tbh
> 
> Agree with that 100%, ace runs with extreme lag on my iPad and monaco crashes. Soooo yeah
> 
> Also should i rename this to performance issues?

Done,

**Comment by CoolCoderSJ** [comment]
> 
> 
> I also want to point out that the colors here are kinda too blue.
> ![image](https://user-images.githubusercontent.com/40917647/106840175-7750c480-6654-11eb-80fa-ef193ead4e5f.png)

We are working on a much better theming platform.

**Comment by alanlichen** [comment]
> > I also want to point out that the colors here are kinda too blue.
> > ![image](https://user-images.githubusercontent.com/40917647/106840175-7750c480-6654-11eb-80fa-ef193ead4e5f.png)
> 
> We are working on a much better theming platform.

Yay 
||but that kinda doesn't relate to the issue anymore||

**Comment by CoolCoderSJ** [comment]
> 
> 
> > > I also want to point out that the colors here are kinda too blue.
> > > [image](https://user-images.githubusercontent.com/40917647/106840175-7750c480-6654-11eb-80fa-ef193ead4e5f.png)
> > 
> > 
> > We are working on a much better theming platform.
> 
> Yay
> ||but that kinda doesn't relate to the issue anymore||

I know, I just thought I would let you know since you said the blue was too blue.

**Comment by leon332157** [comment]
Please checkout `gulp-watch` branch as I have disabled the theme system and HW acceleration to see if that helps with performance.

**Comment by leon332157** [comment]
Resolved
