### ISSUE TITLE
Reflux Marketplace API 

### ISSUE THREAD

**Issue by CoolCoderSJ** [repl-it-discord/repl-it-electron#134]
For the reflux marketplace, the db seems to be kind of broken right now. Will you guys put the light and dark mode separately, or should they also be in the api?

~~dont think i should've created an issue for this but my discord isn't working right now~~

┆Issue is synchronized with this [Trello card](https://trello.com/c/R2BIqmMB) by [Unito](https://www.unito.io/learn-more)

**Comment by spotandjake** [comment]
they should be in the db at the end of the day as it makes it simplier i will probs integrate them else where not through reflux. but they should still be sent via the api

**Comment by CoolCoderSJ** [comment]
Ok, makes sense
