### ISSUE TITLE
app.getAppPath not locating the app properly

### ISSUE THREAD

**Issue by leon332157** [repl-it-discord/repl-it-electron#36]
Expected behavior:
in `src/electron-basic-updater/index.js:14` app.getAppPath should return `dist/dev` when running under developement env with command `electron dist/dev/main.bundle.js`

Actual behavior:
app.getAppPath returns electron default app path `/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/package.json` instead

possaible fix:
run electron with `electron dist/dev` and rename main.bundle.js into main.js

**Comment by eankeen** [comment]
Thanks! :) I pushed 08b9ab876d8402216d0a9a2e40b6bffaaa01dd34 as a quick fix. Does it work now?

Even if it does work, I think we should work towards a more permanent solution

**Comment by leon332157** [comment]
Not working since we still need a package.json file for electron to recognize the directory as an app.

**Comment by leon332157** [comment]
After copying a copy of package.json into dist/dev, the first issue is resolved, but the new issue is caused by requiring package.json
