### ISSUE TITLE
In app updater

### ISSUE THREAD

**Issue by MoniS10** [repl-it-discord/repl-it-electron#74]
Uses Git Fetch and pull the changes in source code and it updates without having to install a new version

**Comment by eankeen** [comment]
not exactly sure what you mean, but i think it would be good to keep app versions we distribute / package and app versions that are in development separate.

i dont see why you would need such a workflow for development, but we do have an updater that updates to the latest released version of the app. right now it may not be working, @leon332157 might be able to give more info on that

**Comment by leon332157** [comment]
It’s being worked on, closing for existing feature.
