### ISSUE TITLE
src/launcher/main.ts doesn't exist

### ISSUE THREAD

**Issue by ArchieMaclean** [repl-it-discord/repl-it-electron#80]
`src/main/bootstrap.js` points to a non-existent file - `../launcher/main.ts`.

**Comment by eankeen** [comment]
hey!

yeah that looks like a mistake, thanks for creating an issue!
i guess it seems that the `dev:main` and `dev:main:watch` npm run scripts will not work for now. ill work on a fix - should be up by the end of the day.

**Comment by ArchieMaclean** [comment]
:+1:

**Comment by leon332157** [comment]
I'll try to fix it but I can gurantee since this is not how electron is supposed to work.

**Comment by eankeen** [comment]
@ArchieMaclean hi! so ill close #80 for now because commit 533ff92a1daf8d9882124a5209922b8334c2a0d9 fixes this issue for me. let me know if you have any other problems :)
