### ISSUE TITLE
enable github wiki - so we can assemble docs and notes?

### ISSUE THREAD

**Issue by jeske** [repl-it-discord/repl-it-electron#82]
Can you enable the github wiki, so we can assemble some docs and notes?

In particular, I'd like some docs of:
- does code run 100% locally on electron?
- how does one use node-ffi or similar inside this IDE to load a native DLL?
- how does one package this repl-it electron container into something that launches the app first, but still has the repl.it dev IDE available?

**Comment by CarlyRaeJepsenStan** [comment]
Hey there!  Thanks for asking.  Unfortunately, I'm not the owner of this repository, but I'll talk to the owner about enabling it.  Then we can add the pertinent wiki pages.

**Comment by leon332157** [comment]
Thanks, I have enabled wiki. This isn't really a local IDE of any sort, it's more like a web browser build with some extra functionalities.

**Comment by jeske** [comment]
Thanks. Perhaps a "intent and capabilities" of the project would be a helpful addition to the README or wiki?

When people go looking for repl.it for electron, I doubt they are looking for a way just to run the web based repl.it inside of an electron container instead of a browser.. because what does that actually give you that you can't get out of making a chrome application shortcut?

I found this project because I'm looking to use an IDE like repl.it to develop standalone Electron applications.. and further, because it would be nice to bundle that IDE right into the standalone app. It's fine if the repl.it IDE itself requires a network connection to the service.. but the app should run standalone in electron.. and ideally there should be a "click to build a package" button that makes the electron packaged app.

**Comment by leon332157** [comment]
Thanks. This is the original plan for where the app is going is adding a local editor like the one on repl.it. But during the reconstruction process with Typescript we have some issues agreeing on the development build system within the collaborators. So the project is halted on development. I would appreciate if anyone could actually use my current build system to replicate my environment on their device and contribute the auto-updater.

**Comment by CarlyRaeJepsenStan** [comment]
> But during the reconstruction process with Typescript ...
I'm curious, what is the advantage in using typescript instead of javascript?

**Comment by jeske** [comment]
Just to be clear, a local-editor is not what I'm talking about. Let me better articulate these two different ideas of what repl.it could do with Electron.

1) make a local version of repl.it IDE, that runs completely offline, for offline development. (involves rewriting lots of repl.it to run client side)

2) use the existing server-side repl.it, to enable development of client-side Electron apps with repl.it inside Electron. (involves making a bundler that will bundle a repl.it app with electron and an installer, and support for client-side electron modules like node-ffi)

I'm talking about #2. @leon332157 I think you're talking about #20 

> I'm curious, what is the advantage in using typescript instead of javascript?

Typechecking.

**Comment by CarlyRaeJepsenStan** [comment]
Yes, one word answers are the most helpful.  -_-
At the moment, the new electron app dev team is probably going to build a separate text editor that runs replit "headless": it will just be a base editor, possibly based off of replit's web ui, and send code to the replit api for execution and display the result.  If (or when) the editor is offline, you will be able to continue using it like any normal editor.

**Comment by jeske** [comment]
On the topic of this issue and the wiki..

When I click on the Wiki tab, it doesn't go to the wiki.. Is it possible there is a wiki permission issue?

**Comment by eankeen** [comment]
it looks like the wiki has not been enabled

so the wiki now has been created. i haven't been following this discussion too closely, but i tried to add the gist of it to the wiki

**Comment by leon332157** [comment]
I’m sorry for late reply but I still don’t quite get your point.
Are you talking about:
1. An IDE that can handle Electron app development.
2. An IDE that can package a repl into an app.
