### ISSUE TITLE
App sometimes gives random syntax errors when writing code

### ISSUE THREAD

**Issue by Warhawk947** [repl-it-discord/repl-it-electron#85]
Sometimes there are random red lines under code that say *unexpected indent*, or *syntax error* that actual aren't true because when I restart the code, it will compile without trouble.

**Comment by NotMoni** [comment]
Hey, @Warhawk947 Could you share us more info?

The most basic info required to debug are : 
- Screenshot of it not working
- Steps to Reproduce the issue
- Your Operating System, and other system info.

This info helps the devs reproduce the issue on their local machine and it can be easier to fix this problem.

You said "Sometimes", so take your time and when it happens again, be sure to screenshot it happening. If your Repl is public, consider sharing the link to it also.

Hope this helps :D

**Comment by Warhawk947** [comment]
nvm it fixed itself
sorry false alarm

**Comment by Warhawk947** [comment]
nvm it fixed itself
sorry false alarm

**Comment by NotMoni** [comment]
Wow

**Comment by RoylatGnail** [comment]
bruh

**Comment by Warhawk947** [comment]
lol sorry guys

**Comment by NotMoni** [comment]
Still tho.
