### ISSUE TITLE
notification doesn't change the page 

### ISSUE THREAD

**Issue by Codemonkey51** [repl-it-discord/repl-it-electron#86]
clicking on a notification doesnt change the page 50% of the time

# reproduce:
goto 1 notification, reply to it then click antother and it wont work.

[video](https://streamable.com/k93vgw)

**Comment by leon332157** [comment]
Thanks for the issue report, the app is currently being reworked for version 2.0, hopefully it will be fixed in a newer version.

**Comment by Codemonkey51** [comment]
YAY

**Comment by leon332157** [comment]
This has been fixed in the newer version.

**Comment by Codemonkey51** [comment]
YAY
