### ISSUE TITLE
Error with the name

### ISSUE THREAD

**Issue by isuckatprogram** [repl-it-discord/repl-it-electron#92]
When i downloaded the windows version and tried to run it, it said this: Windows could not find the file and I think it was because the name has a space in it so I changed the name of the exe file to replit.exe and it worked. So basically I'm saying you need to remove the space in the name

**Comment by isuckatprogram** [comment]
Nevermind, fixing the file to replit.exe didn't fix the issue

**Comment by leon332157** [comment]
Try downloading the file into the download folder and run it.

**Comment by isuckatprogram** [comment]
Thats what I did

**Comment by leon332157** [comment]
Can you hopefully take a screenshot of the error? I would take a look.

**Comment by isuckatprogram** [comment]
I can't reproduce anymore
